# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t tulsipatel/metastaar .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: tulsipatel
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push the Docker image
      run: docker push tulsipatel/metastaar
